# Generated by Django 3.2.15 on 2022-09-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='served_as',
            field=models.IntegerField(choices=[(0, 'draught'), (1, 'bottled')], default=1),
        ),
    ]
