# Generated by Django 3.2.15 on 2022-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_served_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hops',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='served_as',
            field=models.IntegerField(choices=[(1, 'Bottled'), (2, 'Draught')], default=1),
        ),
    ]
